library(shiny)
library(shinydashboard)

sidebar <- shinydashboard::dashboardSidebar(
  shinydashboard::sidebarMenu(
    id = "menue",
    shinydashboard::menuItem("Import",
                             tabName = "tab_import",
                             icon = shiny::icon("download")),
    shinydashboard::menuItem("Filter",
                             tabName = "tab_filter",
                             icon = shiny::icon("filter"),
                             badgeLabel = "x",
                             badgeColor = "red"),
    shinydashboard::menuItem("Metadata",
                             tabName = "tab_metadata",
                             icon = shiny::icon("sitemap"),
                             badgeLabel = "x",
                             badgeColor = "red"),
    shinydashboard::menuItem("Explore",
                             tabName = "tab_explore",
                             icon = shiny::icon("compass"),
                             badgeLabel = "x",
                             badgeColor = "red"),
    shinydashboard::menuItem("LOQ",
                             tabName = "tab_loq",
                             icon = shiny::icon("exchange-alt"),
                             badgeLabel = "x",
                             badgeColor = "red"),
    shinydashboard::menuItem("Parameter Wizard",
                             tabName = "tab_wizard",
                             icon = shiny::icon("magic"),
                             badgeLabel = "x",
                             badgeColor = "red"),
    shinydashboard::menuItem("Transformation",
                             tabName = "tab_trafo",
                             icon = shiny::icon(name = "random", class = "fas"),
                             badgeLabel = "x",
                             badgeColor = "red"),
    shinydashboard::menuItem("Fill Missings",
                             tabName = "tab_tidy",
                             icon = shiny::icon("fill-drip"),
                             badgeLabel = "x",
                             badgeColor = "red"),
    shinydashboard::menuItem("Detect Outliers",
                             tabName = "tab_revise",
                             icon = shiny::icon("microscope"),
                             badgeLabel = "x",
                             badgeColor = "red"),
    shinydashboard::menuItem("Correlation",
                             tabName = "tab_correlation",
                             icon = shiny::icon("chart-bar"),
                             badgeLabel = "x",
                             badgeColor = "red"),
    shinydashboard::menuItem("Regression",
                             tabName = "tab_regression",
                             icon = shiny::icon("chart-line"),
                             badgeLabel = "x",
                             badgeColor = "red"),
    shinydashboard::menuItem("Export",
                             tabName = "tab_export",
                             icon = shiny::icon("upload"),
                             badgeLabel = "x",
                             badgeColor = "red")

  )
)
